/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'sao-glyphs\'">' + entity + '</span>' + html;
	}
	var icons = {
		'btn-armor': '&#xe900;',
		'btn-avatar': '&#xe901;',
		'btn-blade': '&#xe902;',
		'btn-blade-dual': '&#xe903;',
		'btn-blade-parrying': '&#xe904;',
		'btn-blade-thowing': '&#xe905;',
		'btn-cancel': '&#xe906;',
		'btn-cancel-extrude': '&#xe907;',
		'btn-checked': '&#xe908;',
		'btn-close': '&#xe909;',
		'btn-config': '&#xe90a;',
		'btn-confirm': '&#xe90b;',
		'btn-confirm-extrude': '&#xe90c;',
		'btn-details': '&#xe90d;',
		'btn-dungeon': '&#xe90e;',
		'btn-empty': '&#xe90f;',
		'btn-equipment': '&#xe910;',
		'btn-exclamation': '&#xe911;',
		'btn-foward': '&#xe912;',
		'btn-friend-add': '&#xe913;',
		'btn-friend-remove': '&#xe914;',
		'btn-group': '&#xe915;',
		'btn-guild': '&#xe916;',
		'btn-healing-battle': '&#xe917;',
		'btn-help': '&#xe918;',
		'btn-invite': '&#xe919;',
		'btn-itens': '&#xe91a;',
		'btn-list': '&#xe91b;',
		'btn-logout': '&#xe91c;',
		'btn-map': '&#xe91d;',
		'btn-map-gps': '&#xe91e;',
		'btn-message': '&#xe91f;',
		'btn-minus': '&#xe920;',
		'btn-necklace': '&#xe921;',
		'btn-options': '&#xe922;',
		'btn-party': '&#xe923;',
		'btn-paused': '&#xe924;',
		'btn-plus': '&#xe925;',
		'btn-quest': '&#xe926;',
		'btn-question': '&#xe927;',
		'btn-radar': '&#xe928;',
		'btn-raid': '&#xe929;',
		'btn-reverse': '&#xe92a;',
		'btn-ringed-armor': '&#xe92b;',
		'btn-ringed-avatar': '&#xe92c;',
		'btn-ringed-blade': '&#xe92d;',
		'btn-ringed-blade-dual': '&#xe92e;',
		'btn-ringed-blade-parrying': '&#xe92f;',
		'btn-ringed-blade-thowing': '&#xe930;',
		'btn-ringed-cancel': '&#xe931;',
		'btn-ringed-cancel-extrude': '&#xe932;',
		'btn-ringed-checked': '&#xe933;',
		'btn-ringed-close': '&#xe934;',
		'btn-ringed-config': '&#xe935;',
		'btn-ringed-confirm': '&#xe936;',
		'btn-ringed-confirm-extrude': '&#xe937;',
		'btn-ringed-details': '&#xe938;',
		'btn-ringed-dungeon': '&#xe939;',
		'btn-ringed-empty': '&#xe93a;',
		'btn-ringed-equipment': '&#xe93b;',
		'btn-ringed-exclamation': '&#xe93c;',
		'btn-ringed-foward': '&#xe93d;',
		'btn-ringed-friend-add': '&#xe93e;',
		'btn-ringed-friend-remove': '&#xe93f;',
		'btn-ringed-group': '&#xe940;',
		'btn-ringed-guild': '&#xe941;',
		'btn-ringed-healing-battle': '&#xe942;',
		'btn-ringed-help': '&#xe943;',
		'btn-ringed-invite': '&#xe944;',
		'btn-ringed-itens': '&#xe945;',
		'btn-ringed-list': '&#xe946;',
		'btn-ringed-logout': '&#xe947;',
		'btn-ringed-map': '&#xe948;',
		'btn-ringed-map-gps': '&#xe949;',
		'btn-ringed-message': '&#xe94a;',
		'btn-ringed-minus': '&#xe94b;',
		'btn-ringed-necklace': '&#xe94c;',
		'btn-ringed-options': '&#xe94d;',
		'btn-ringed-party': '&#xe94e;',
		'btn-ringed-pause': '&#xe94f;',
		'btn-ringed-plus': '&#xe950;',
		'btn-ringed-quest': '&#xe951;',
		'btn-ringed-question': '&#xe952;',
		'btn-ringed-radar': '&#xe953;',
		'btn-ringed-raid': '&#xe954;',
		'btn-ringed-reverse': '&#xe955;',
		'btn-ringed-shirt': '&#xe956;',
		'btn-ringed-signal': '&#xe957;',
		'btn-ringed-skill': '&#xe958;',
		'btn-ringed-start': '&#xe959;',
		'btn-ringed-stop': '&#xe95a;',
		'btn-ringed-tracking': '&#xe95b;',
		'btn-ringed-zoom-in': '&#xe95c;',
		'btn-ringed-zoom-out': '&#xe95d;',
		'btn-shirt': '&#xe95e;',
		'btn-signal': '&#xe95f;',
		'btn-skill': '&#xe960;',
		'btn-start': '&#xe961;',
		'btn-stop': '&#xe962;',
		'btn-tracking': '&#xe963;',
		'btn-zoom-in': '&#xe964;',
		'btn-zoom-out': '&#xe965;',
		'icon-armor': '&#xe966;',
		'icon-avatar': '&#xe967;',
		'icon-blade': '&#xe968;',
		'icon-blade-dual': '&#xe969;',
		'icon-blade-parrying': '&#xe96a;',
		'icon-blade-throwing': '&#xe96b;',
		'icon-cancel': '&#xe96c;',
		'icon-checked': '&#xe96d;',
		'icon-close': '&#xe96e;',
		'icon-config': '&#xe96f;',
		'icon-confirm': '&#xe970;',
		'icon-details': '&#xe971;',
		'icon-dungeon': '&#xe972;',
		'icon-empty': '&#xe973;',
		'icon-equipment': '&#xe974;',
		'icon-exclamation': '&#xe975;',
		'icon-foward': '&#xe976;',
		'icon-friend-add': '&#xe977;',
		'icon-friend-remove': '&#xe978;',
		'icon-group': '&#xe979;',
		'icon-guild': '&#xe97a;',
		'icon-healing-battle': '&#xe97b;',
		'icon-help': '&#xe97c;',
		'icon-invite': '&#xe97d;',
		'icon-itens': '&#xe97e;',
		'icon-list': '&#xe97f;',
		'icon-logout': '&#xe980;',
		'icon-map': '&#xe981;',
		'icon-map-gps': '&#xe982;',
		'icon-message': '&#xe983;',
		'icon-minus': '&#xe984;',
		'icon-necklace': '&#xe985;',
		'icon-options': '&#xe986;',
		'icon-party': '&#xe987;',
		'icon-paused': '&#xe988;',
		'icon-plus': '&#xe989;',
		'icon-quest': '&#xe98a;',
		'icon-question': '&#xe98b;',
		'icon-radar': '&#xe98c;',
		'icon-raid': '&#xe98d;',
		'icon-reverse': '&#xe98e;',
		'icon-signal': '&#xe98f;',
		'icon-skill': '&#xe990;',
		'icon-start': '&#xe991;',
		'icon-status-bar2': '&#xe992;',
		'icon-stop': '&#xe993;',
		'icon-tracking': '&#xe994;',
		'icon-zoom-in': '&#xe995;',
		'icon-zoom-out': '&#xe996;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
