/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'sao-glyphs\'">' + entity + '</span>' + html;
	}
	var icons = {
		'sao-btn-armor': '&#xe901;',
		'sao-btn-armor-ringed': '&#xe902;',
		'sao-btn-avatar': '&#xe903;',
		'sao-btn-avatar-ringed': '&#xe904;',
		'sao-btn-blade': '&#xe905;',
		'sao-btn-blade-dual-ringed': '&#xe906;',
		'sao-btn-blade-dual': '&#xe900;',
		'sao-btn-blade-parrying': '&#xe907;',
		'sao-btn-blade-parrying-ringed': '&#xe908;',
		'sao-btn-blade-ringed': '&#xe909;',
		'sao-btn-blade-thowing': '&#xe90a;',
		'sao-btn-blade-thowing-ringed': '&#xe90b;',
		'sao-btn-cancel': '&#xe90c;',
		'sao-btn-cancel-extrude': '&#xe90d;',
		'sao-btn-cancel-extrude-ringed': '&#xe90e;',
		'sao-btn-cancel-ringed': '&#xe90f;',
		'sao-btn-checked': '&#xe910;',
		'sao-btn-checked-ringed': '&#xe911;',
		'sao-btn-close': '&#xe912;',
		'sao-btn-close-ringed': '&#xe913;',
		'sao-btn-config': '&#xe914;',
		'sao-btn-config-ringed': '&#xe915;',
		'sao-btn-confirm': '&#xe916;',
		'sao-btn-confirm-extrude': '&#xe917;',
		'sao-btn-confirm-extrude-ringed': '&#xe918;',
		'sao-btn-confirm-ringed': '&#xe919;',
		'sao-btn-details': '&#xe91a;',
		'sao-btn-details-ringed': '&#xe91b;',
		'sao-btn-dungeon': '&#xe91c;',
		'sao-btn-dungeon-ringed': '&#xe91d;',
		'sao-btn-empty': '&#xe91e;',
		'sao-btn-empty-ringed': '&#xe91f;',
		'sao-btn-equipment': '&#xe920;',
		'sao-btn-equipment-ringed': '&#xe921;',
		'sao-btn-exclamation': '&#xe922;',
		'sao-btn-exclamation-ringed': '&#xe923;',
		'sao-btn-foward': '&#xe924;',
		'sao-btn-foward-ringed': '&#xe925;',
		'sao-btn-friend-add': '&#xe926;',
		'sao-btn-friend-add-ringed': '&#xe927;',
		'sao-btn-friend-remove': '&#xe928;',
		'sao-btn-friend-remove-ringed': '&#xe929;',
		'sao-btn-group': '&#xe92a;',
		'sao-btn-group-ringed': '&#xe92b;',
		'sao-btn-guild': '&#xe92c;',
		'sao-btn-guild-ringed': '&#xe92d;',
		'sao-btn-healing-battle': '&#xe92e;',
		'sao-btn-healing-battle-ringed': '&#xe92f;',
		'sao-btn-help': '&#xe930;',
		'sao-btn-help-ringed': '&#xe931;',
		'sao-btn-invite': '&#xe932;',
		'sao-btn-invite-ringed': '&#xe933;',
		'sao-btn-itens': '&#xe934;',
		'sao-btn-itens-ringed': '&#xe935;',
		'sao-btn-list': '&#xe936;',
		'sao-btn-list-ringed': '&#xe937;',
		'sao-btn-logout': '&#xe938;',
		'sao-btn-logout-ringed': '&#xe939;',
		'sao-btn-map': '&#xe93a;',
		'sao-btn-map_ringed': '&#xe93b;',
		'sao-btn-map-gps': '&#xe93c;',
		'sao-btn-map-gps-ringed': '&#xe93d;',
		'sao-btn-message': '&#xe93e;',
		'sao-btn-message-ringed': '&#xe93f;',
		'sao-btn-minus': '&#xe940;',
		'sao-btn-minus-ringed': '&#xe941;',
		'sao-btn-necklace': '&#xe942;',
		'sao-btn-necklace-ringed': '&#xe943;',
		'sao-btn-options': '&#xe944;',
		'sao-btn-options-ringed': '&#xe945;',
		'sao-btn-party': '&#xe946;',
		'sao-btn-party-ringed': '&#xe947;',
		'sao-btn-paused': '&#xe948;',
		'sao-btn-pause-ringed': '&#xe949;',
		'sao-btn-plus': '&#xe94a;',
		'sao-btn-plus-ringed': '&#xe94b;',
		'sao-btn-quest': '&#xe94c;',
		'sao-btn-question': '&#xe94d;',
		'sao-btn-question-ringed': '&#xe94e;',
		'sao-btn-quest-ringed': '&#xe94f;',
		'sao-btn-radar': '&#xe950;',
		'sao-btn-radar-ringed': '&#xe951;',
		'sao-btn-raid': '&#xe952;',
		'sao-btn-raid-ringed': '&#xe953;',
		'sao-btn-reverse': '&#xe954;',
		'sao-btn-reverse-ringed': '&#xe955;',
		'sao-btn-shirt': '&#xe956;',
		'sao-btn-shirt-ringed': '&#xe957;',
		'sao-btn-signal': '&#xe958;',
		'sao-btn-signal-ringed': '&#xe959;',
		'sao-btn-skill': '&#xe95a;',
		'sao-btn-skill-ringed': '&#xe95b;',
		'sao-btn-start': '&#xe95c;',
		'sao-btn-start-ringed': '&#xe95d;',
		'sao-btn-stop': '&#xe95e;',
		'sao-btn-stop-ringed': '&#xe95f;',
		'sao-btn-tracking': '&#xe960;',
		'sao-btn-tracking-ringed': '&#xe961;',
		'sao-btn-zoom-in': '&#xe962;',
		'sao-btn-zoom-in-ringed': '&#xe963;',
		'sao-btn-zoom-out': '&#xe964;',
		'sao-btn-zoom-out-ringed': '&#xe965;',
		'sao-icon-armor': '&#xe966;',
		'sao-icon-avatar': '&#xe967;',
		'sao-icon-blade': '&#xe968;',
		'sao-icon-blade-dual': '&#xe969;',
		'sao-icon-blade-parrying': '&#xe96a;',
		'sao-icon-blade-throwing': '&#xe96b;',
		'sao-icon-cancel': '&#xe96c;',
		'sao-icon-checked': '&#xe96d;',
		'sao-icon-close': '&#xe96e;',
		'sao-icon-config': '&#xe96f;',
		'sao-icon-confirm': '&#xe970;',
		'sao-icon-details': '&#xe971;',
		'sao-icon-dungeon': '&#xe972;',
		'sao-icon-empty': '&#xe973;',
		'sao-icon-equipment': '&#xe974;',
		'sao-icon-exclamation': '&#xe975;',
		'sao-icon-foward': '&#xe976;',
		'sao-icon-friend-add': '&#xe977;',
		'sao-icon-friend-remove': '&#xe978;',
		'sao-icon-group': '&#xe979;',
		'sao-icon-guild': '&#xe97a;',
		'sao-icon-healing-battle': '&#xe97b;',
		'sao-icon-help': '&#xe97c;',
		'sao-icon-invite': '&#xe97d;',
		'sao-icon-itens': '&#xe97e;',
		'sao-icon-list': '&#xe97f;',
		'sao-icon-logout': '&#xe980;',
		'sao-icon-map': '&#xe981;',
		'sao-icon-map-gps': '&#xe982;',
		'sao-icon-message': '&#xe983;',
		'sao-icon-minus': '&#xe984;',
		'sao-icon-necklace': '&#xe985;',
		'sao-icon-options': '&#xe986;',
		'sao-icon-party': '&#xe987;',
		'sao-icon-paused': '&#xe988;',
		'sao-icon-plus': '&#xe989;',
		'sao-icon-quest': '&#xe98a;',
		'sao-icon-question': '&#xe98b;',
		'sao-icon-radar': '&#xe98c;',
		'sao-icon-raid': '&#xe98d;',
		'sao-icon-reverse': '&#xe98e;',
		'sao-icon-signal': '&#xe98f;',
		'sao-icon-skill': '&#xe990;',
		'sao-icon-start': '&#xe991;',
		'sao-icon-status-bar2': '&#xe992;',
		'sao-icon-stop': '&#xe993;',
		'sao-icon-tracking': '&#xe994;',
		'sao-icon-zoom-in': '&#xe995;',
		'sao-icon-zoom-out': '&#xe996;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/sao-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
