/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'sao-glyphs\'">' + entity + '</span>' + html;
	}
	var icons = {
		'sao-btn-alert': '&#xe900;',
		'sao-btn-armor': '&#xe901;',
		'sao-btn-avatar': '&#xe902;',
		'sao-btn-battle-healing': '&#xe903;',
		'sao-btn-before': '&#xe904;',
		'sao-btn-belt': '&#xe905;',
		'sao-btn-blade': '&#xe906;',
		'sao-btn-blade-dual': '&#xe907;',
		'sao-btn-blade-parrying': '&#xe908;',
		'sao-btn-blade-throwing': '&#xe909;',
		'sao-btn-brightness': '&#xe90a;',
		'sao-btn-calendar': '&#xe90b;',
		'sao-btn-cancel': '&#xe90c;',
		'sao-btn-clock': '&#xe90d;',
		'sao-btn-confirm': '&#xe90e;',
		'sao-btn-contrast': '&#xe90f;',
		'sao-btn-correct': '&#xe910;',
		'sao-btn-cross': '&#xe911;',
		'sao-btn-details': '&#xe912;',
		'sao-btn-dices': '&#xe913;',
		'sao-btn-dungeon': '&#xe914;',
		'sao-btn-elemental-air': '&#xe915;',
		'sao-btn-elemental-earth': '&#xe916;',
		'sao-btn-elemental-fire': '&#xe917;',
		'sao-btn-elemental-nature': '&#xe918;',
		'sao-btn-elemental-void': '&#xe919;',
		'sao-btn-elemental-water': '&#xe91a;',
		'sao-btn-equipament': '&#xe91b;',
		'sao-btn-evil': '&#xe91c;',
		'sao-btn-exclamation': '&#xe91d;',
		'sao-btn-foward': '&#xe91e;',
		'sao-btn-friend-add': '&#xe91f;',
		'sao-btn-friend-remove': '&#xe920;',
		'sao-btn-gps': '&#xe921;',
		'sao-btn-group': '&#xe922;',
		'sao-btn-guild': '&#xe923;',
		'sao-btn-heart': '&#xe924;',
		'sao-btn-help': '&#xe925;',
		'sao-btn-info': '&#xe926;',
		'sao-btn-invite': '&#xe927;',
		'sao-btn-itens': '&#xe928;',
		'sao-btn-life-status': '&#xe929;',
		'sao-btn-list': '&#xe92a;',
		'sao-btn-list-down': '&#xe92b;',
		'sao-btn-list-up': '&#xe92c;',
		'sao-btn-loading': '&#xe92d;',
		'sao-btn-logout': '&#xe92e;',
		'sao-btn-mail': '&#xe92f;',
		'sao-btn-mail-open': '&#xe930;',
		'sao-btn-map': '&#xe931;',
		'sao-btn-message': '&#xe932;',
		'sao-btn-mic': '&#xe933;',
		'sao-btn-mic-muted': '&#xe934;',
		'sao-btn-mic-volume-down': '&#xe935;',
		'sao-btn-mic-volume-up': '&#xe936;',
		'sao-btn-minus': '&#xe937;',
		'sao-btn-necklace': '&#xe938;',
		'sao-btn-next': '&#xe939;',
		'sao-btn-options': '&#xe93a;',
		'sao-btn-party': '&#xe93b;',
		'sao-btn-phone': '&#xe93c;',
		'sao-btn-plus': '&#xe93d;',
		'sao-btn-power': '&#xe93e;',
		'sao-btn-quest': '&#xe93f;',
		'sao-btn-question': '&#xe940;',
		'sao-btn-radar': '&#xe941;',
		'sao-btn-reverse': '&#xe942;',
		'sao-btn-ring': '&#xe943;',
		'sao-btn-settings': '&#xe944;',
		'sao-btn-share': '&#xe945;',
		'sao-btn-shield': '&#xe946;',
		'sao-btn-signal': '&#xe947;',
		'sao-btn-skill': '&#xe948;',
		'sao-btn-social-android': '&#xe949;',
		'sao-btn-social-delicius': '&#xe94a;',
		'sao-btn-social-deviantart': '&#xe94b;',
		'sao-btn-social-facebook': '&#xe94c;',
		'sao-btn-social-flickr': '&#xe94d;',
		'sao-btn-social-google': '&#xe94e;',
		'sao-btn-social-googledrive': '&#xe94f;',
		'sao-btn-social-googleplay': '&#xe950;',
		'sao-btn-social-googleplus': '&#xe951;',
		'sao-btn-social-hangouts': '&#xe952;',
		'sao-btn-social-line': '&#xe953;',
		'sao-btn-social-netflix': '&#xe954;',
		'sao-btn-social-playstation': '&#xe955;',
		'sao-btn-social-podcasts': '&#xe956;',
		'sao-btn-social-skype': '&#xe957;',
		'sao-btn-social-spotify': '&#xe958;',
		'sao-btn-social-twitter': '&#xe959;',
		'sao-btn-social-vine': '&#xe95a;',
		'sao-btn-social-whatsapp': '&#xe95b;',
		'sao-btn-social-wikipedia': '&#xe95c;',
		'sao-btn-social-windows': '&#xe95d;',
		'sao-btn-social-xbox': '&#xe95e;',
		'sao-btn-social-youtube': '&#xe95f;',
		'sao-btn-start': '&#xe960;',
		'sao-btn-statistic-columns': '&#xe961;',
		'sao-btn-status-bar2': '&#xe962;',
		'sao-btn-stop': '&#xe963;',
		'sao-btn-target': '&#xe964;',
		'sao-btn-text-align-center': '&#xe965;',
		'sao-btn-text-align-justify': '&#xe966;',
		'sao-btn-text-align-left': '&#xe967;',
		'sao-btn-text-align-right': '&#xe968;',
		'sao-btn-timer': '&#xe969;',
		'sao-btn-tracking': '&#xe96a;',
		'sao-btn-volume-down': '&#xe96b;',
		'sao-btn-volume-mute': '&#xe96c;',
		'sao-btn-volume-up': '&#xe96d;',
		'sao-btn-zoom-in': '&#xe96e;',
		'sao-btn-zoom-out': '&#xe96f;',
		'sao-icon-alert': '&#xe970;',
		'sao-icon-armor': '&#xe971;',
		'sao-icon-avatar': '&#xe972;',
		'sao-icon-battle-healing': '&#xe973;',
		'sao-icon-before': '&#xe974;',
		'sao-icon-belt': '&#xe975;',
		'sao-icon-blade': '&#xe976;',
		'sao-icon-blade-dual': '&#xe977;',
		'sao-icon-blade-parrying': '&#xe978;',
		'sao-icon-blade-throwing': '&#xe979;',
		'sao-icon-brightness': '&#xe97a;',
		'sao-icon-calendar': '&#xe97b;',
		'sao-icon-cancel': '&#xe97c;',
		'sao-icon-clock': '&#xe97d;',
		'sao-icon-confirm': '&#xe97e;',
		'sao-icon-contrast': '&#xe97f;',
		'sao-icon-correct': '&#xe980;',
		'sao-icon-cross': '&#xe981;',
		'sao-icon-details': '&#xe982;',
		'sao-icon-dices': '&#xe983;',
		'sao-icon-dungeon': '&#xe984;',
		'sao-icon-elemental-air': '&#xe985;',
		'sao-icon-elemental-earth': '&#xe986;',
		'sao-icon-elemental-fire': '&#xe987;',
		'sao-icon-elemental-nature': '&#xe988;',
		'sao-icon-elemental-void': '&#xe989;',
		'sao-icon-elemental-water': '&#xe98a;',
		'sao-icon-equipament': '&#xe98b;',
		'sao-icon-evil': '&#xe98c;',
		'sao-icon-exclamation': '&#xe98d;',
		'sao-icon-foward': '&#xe98e;',
		'sao-icon-friend-add': '&#xe98f;',
		'sao-icon-friend-remove': '&#xe990;',
		'sao-icon-gps': '&#xe991;',
		'sao-icon-group': '&#xe992;',
		'sao-icon-guild': '&#xe993;',
		'sao-icon-heart': '&#xe994;',
		'sao-icon-help': '&#xe995;',
		'sao-icon-info': '&#xe996;',
		'sao-icon-invite': '&#xe997;',
		'sao-icon-itens': '&#xe998;',
		'sao-icon-life-status': '&#xe999;',
		'sao-icon-list': '&#xe99a;',
		'sao-icon-list-down': '&#xe99b;',
		'sao-icon-list-up': '&#xe99c;',
		'sao-icon-loading': '&#xe99d;',
		'sao-icon-logout': '&#xe99e;',
		'sao-icon-mail': '&#xe99f;',
		'sao-icon-mail-open': '&#xe9a0;',
		'sao-icon-map': '&#xe9a1;',
		'sao-icon-message': '&#xe9a2;',
		'sao-icon-mic': '&#xe9a3;',
		'sao-icon-mic-muted': '&#xe9a4;',
		'sao-icon-mic-volume-down': '&#xe9a5;',
		'sao-icon-mic-volume-up': '&#xe9a6;',
		'sao-icon-minus': '&#xe9a7;',
		'sao-icon-necklace': '&#xe9a8;',
		'sao-icon-next': '&#xe9a9;',
		'sao-icon-options': '&#xe9aa;',
		'sao-icon-party': '&#xe9ab;',
		'sao-icon-phone': '&#xe9ac;',
		'sao-icon-plus': '&#xe9ad;',
		'sao-icon-power': '&#xe9ae;',
		'sao-icon-quest': '&#xe9af;',
		'sao-icon-question': '&#xe9b0;',
		'sao-icon-radar': '&#xe9b1;',
		'sao-icon-reverse': '&#xe9b2;',
		'sao-icon-ring': '&#xe9b3;',
		'sao-icon-settings': '&#xe9b4;',
		'sao-icon-share': '&#xe9b5;',
		'sao-icon-shield': '&#xe9b6;',
		'sao-icon-signal': '&#xe9b7;',
		'sao-icon-skill': '&#xe9b8;',
		'sao-icon-social-android': '&#xe9b9;',
		'sao-icon-social-delicius': '&#xe9ba;',
		'sao-icon-social-deviantart': '&#xe9bb;',
		'sao-icon-social-facebook': '&#xe9bc;',
		'sao-icon-social-flickr': '&#xe9bd;',
		'sao-icon-social-google': '&#xe9be;',
		'sao-icon-social-googledrive': '&#xe9bf;',
		'sao-icon-social-googleplay': '&#xe9c0;',
		'sao-icon-social-googleplus': '&#xe9c1;',
		'sao-icon-social-hangouts': '&#xe9c2;',
		'sao-icon-social-line': '&#xe9c3;',
		'sao-icon-social-netflix': '&#xe9c4;',
		'sao-icon-social-playstation': '&#xe9c5;',
		'sao-icon-social-podcasts': '&#xe9c6;',
		'sao-icon-social-skype': '&#xe9c7;',
		'sao-icon-social-spotify': '&#xe9c8;',
		'sao-icon-social-twitter': '&#xe9c9;',
		'sao-icon-social-vine': '&#xe9ca;',
		'sao-icon-social-whatsapp': '&#xe9cb;',
		'sao-icon-social-wikipedia': '&#xe9cc;',
		'sao-icon-social-windows': '&#xe9cd;',
		'sao-icon-social-xbox': '&#xe9ce;',
		'sao-icon-social-youtube': '&#xe9cf;',
		'sao-icon-star': '&#xe9d0;',
		'sao-icon-start': '&#xe9d1;',
		'sao-icon-statistic-columns': '&#xe9d2;',
		'sao-icon-status-bar2': '&#xe9d3;',
		'sao-icon-stop': '&#xe9d4;',
		'sao-icon-target': '&#xe9d5;',
		'sao-icon-text-align-center': '&#xe9d6;',
		'sao-icon-text-align-justify': '&#xe9d7;',
		'sao-icon-text-align-left': '&#xe9d8;',
		'sao-icon-text-align-right': '&#xe9d9;',
		'sao-icon-timer': '&#xe9da;',
		'sao-icon-tracking': '&#xe9db;',
		'sao-icon-volume-down': '&#xe9dc;',
		'sao-icon-volume-mute': '&#xe9dd;',
		'sao-icon-volume-up': '&#xe9de;',
		'sao-icon-zoom-in': '&#xe9df;',
		'sao-icon-zoom-out': '&#xe9e0;',
		'sao-ring-avatar': '&#xe9e1;',
		'sao-ring-cancel': '&#xe9e2;',
		'sao-ring-confirm': '&#xe9e3;',
		'sao-ring-gps': '&#xe9e4;',
		'sao-ring-group': '&#xe9e5;',
		'sao-ring-itens': '&#xe9e6;',
		'sao-ring-message': '&#xe9e7;',
		'sao-ring-settings': '&#xe9e8;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/sao-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
